version: '3.8'

services:
  postgres:
    image: postgres:18-alpine
    container_name: nac_postgres
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - nac_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:8-alpine
    container_name: nac_redis
    volumes:
      - redisdata:/data
    networks:
      - nac_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: nac_api
    env_file:
      - .env
    ports:
      - "8000:8000"
    networks:
       nac_network:
         aliases:
          - api
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/users"]
      interval: 10s
      timeout: 5s
      retries: 3

  freeradius:
   build: 
      context: ./radius/raddb
   container_name: nac_freeradius
   volumes:
      - ./radius/raddb:/etc/freeradius
   ports:
      - "1812:1812/udp"
      - "1813:1813/udp"
   networks:
      - nac_network
   depends_on:
      api:
        condition: service_healthy

networks:
  nac_network:
    driver: bridge

volumes:
  pgdata:
  redisdata:
  freeradius_data: